### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by tyeeman** [Innovacy/Up#1]
I've read your instructions and I copy all files to my localhost/subfolder but I get errors on accessing index.php. Something about "require "vendor/autoload.php". I am not using composer to install. I'm on windows 7 and just copy files to install cms's like this. What do I have to download and copy to install Up? There is also no config.json file anywhere I can see? Do I have to have "mdwiki" also in the main folder for Up to work?

This looks like a great cms if I can get it working. Thanks for writing it!

**Comment by dkarvounaris** [comment]
You should use composer to install all dependencies and have the autoload file created, which will include all classes. You don't need mdwiki, it's independent from it.

Composer will download https://github.com/cebe/markdown and install it under vendor/cebe/markdown - it is used for basic markup rendering, advanced by Up's classes with some additonal functionality. 

If you want to do it manually, you will have to put this project in a subfolder and then create a similar autoload file by hand (which I don't suggest). 

Please let me know, if you really can't use composer (it's possible under Windows though, I do it all the time as I develop under windows 7 too). I might create an "unpack-and-ready" release that has all dependencies included then,

**Comment by dkarvounaris** [comment]
Hum I need to add this to the documentation... sorry I forgot about this one. This needs improvement.

**Comment by dkarvounaris** [comment]
Regarding the config.json, you just create it, one in the main folder and anywhere in subfolders, where you might want to overwrite specific configurations.

**Comment by tyeeman** [comment]
Yes, an "unpack and ready" zip file would be great for me. Looks like only lib-pcre and cebe/markdown, then the autoload stuff is all that's required, which may be only a few files?

**Comment by tyeeman** [comment]
Ok, I managed to install composer and run it to get the dependencies. I went through the instructions again and added config.json file with the settings described. I now go to index and I get an error about Up/navigation.php using markdown

`Fatal error: Cannot use cebe\markdown\Markdown as Markdown because the name is already in use in G:\web\Uwamp\www\up\Up\Navigation.php on line 26`

so I commented out line 26 in that file. I reload then I get 404 file not found. What to do next? I get no errors shown to point me in the right direction.

**Comment by dkarvounaris** [comment]
Obsolete, Version 2 won't require composer and is available as pre-release.

**Comment by tyeeman** [comment]
Thanks for doing this! Just installed in UWAMP and I still get an error on accessing index.php. 

![uperror](https://cloud.githubusercontent.com/assets/4469306/17829017/d358fa68-6654-11e6-843d-a3dcc6c6cfb1.png)

**Comment by dkarvounaris** [comment]
Ah it's good to see you back, didn't expect you to be still at it :) 

The error you got was strange, because this works flawlessly for me. Finally, after some research I figured out that it's a bug in PHP when running without the Opcache, while with the Opcache active it does not throw this error.  https://bugs.php.net/bug.php?id=66773

I will make a change in the code in the next minutes and it should be working then. Please test it for me as I have no installation without Opcache. Please download it directly from the current dev branch (won't update the last pre-release zip package yet). 

There will be many more updates these days.

**Comment by dkarvounaris** [comment]
It's fixed. Please let me know if it works now.

**Comment by tyeeman** [comment]
Ok, just tried it and another error -
![uperror](https://cloud.githubusercontent.com/assets/4469306/17834570/a333c744-66fb-11e6-94c8-f78ae95d76e0.png)

RewriteBase is also set - RewriteBase /up

**Comment by tyeeman** [comment]
Sorry didn't mean to close this, hit the wrong button.

**Comment by dkarvounaris** [comment]
Is there the page.tpl file existent in the main folder you installed it?
This may have to do something with being installed on windows or in a subfolder. I will have to test these cases myself.

**Comment by tyeeman** [comment]
Yes, page.tpl is there. I will upload to my web space and see what happens there.

Update - same error there - 

Fatal error: Uncaught exception 'RuntimeException' with message 'File page.tpl not found, but is required' in /home/wed/public_html/site.net/up/src/Up/App.php:188 Stack trace: #0 /home/wed/public_html/site.net/up/index.php(38): Innovacy\Up\App->run() #1 {main} thrown in /home/wed/public_html/site.net/up/src/Up/App.php on line 188

**Comment by tyeeman** [comment]
Where is basePath set?

**Comment by dkarvounaris** [comment]
Issue fixed. Please test now. I created a new pre-release to download, as there are quite some new developments and features by now since the last one. There may be though some unknown errors even though tested, it's still a pre-release and quite some things refactored.

**Comment by tyeeman** [comment]
Error on line 210 now - 

![uperror](https://cloud.githubusercontent.com/assets/4469306/17834690/c9312950-6700-11e6-91fa-fd86548449ee.png)

**Comment by dkarvounaris** [comment]
Also on your linux install?

**Comment by tyeeman** [comment]
Just checked, yes, same.

**Comment by dkarvounaris** [comment]
So, I have been checking and checking but I could not reproduce it, until I called the domain with index.php in the URL for another reason and got that error. This file however should not be called directly, Just call for testing http://yourdomain.com/docs/ ... if the .htaccess is there and applied in your apache, then you should see the documentation. Otherwise, please check that your apache is correctly configured to not ignore .htaccess files and has mod_rewrite enabled (rarely not the case these days).

**Comment by dkarvounaris** [comment]
... and, just in case some server does not provide the right values, I have improved the basepath function too in the latest dev branch.

**Comment by tyeeman** [comment]
Ok, had to add 

```
date_default_timezone_set('America/Los_Angeles');
```

to line 26 in App.php. I then get --

![2016-08-22_230825](https://cloud.githubusercontent.com/assets/4469306/17881884/9f5243e4-68bd-11e6-836f-b270694a00d9.png)

Viewing docs works fine.
Is there any simple way to use Up as a blog?

**Comment by dkarvounaris** [comment]
Perfect, it works for you then. 
I suggest to read through the NEW documentation, that is by far better (still rewriting parts of it though, but the basics should cover things missing before) and it should help you get started.

Start by creating an index.md in the main folder for your content, that will replace the 404. From there just create further documents as you need. The files in the docs folder should give you some examples for most things (more when version 2 is fully ready).

And yes, you can use it for any type of site you want, even a simple blog. It may work for some though better than for others. It's not made to replace something like Wordpress. If you prefer a WYSIWYG editor, you can use https://stackedit.io/ to create your Markdown. 

If you encounter any more issues, please create a new ticket.
